"""
rss_service.py

Generates a valid RSS 2.0 feed from a user's podcast library.
The feed includes <enclosure> tags so it works in any podcast app
(Pocket Casts, Overcast, Apple Podcasts, etc.)

Usage:
    xml = build_rss_feed(podcasts, user_id)
"""

from datetime import datetime, timezone
from xml.etree.ElementTree import Element, SubElement, tostring
from xml.dom.minidom import parseString


def _fmt_rfc2822(dt_str: str) -> str:
    """Convert a Supabase ISO timestamp to RFC 2822 (required by RSS spec)."""
    try:
        dt = datetime.fromisoformat(dt_str.replace("Z", "+00:00"))
    except Exception:
        dt = datetime.now(timezone.utc)
    return dt.strftime("%a, %d %b %Y %H:%M:%S +0000")


def build_rss_feed(podcasts, user_id, base_url, token):
    """
    Args:
        podcasts:  List of podcast rows from Supabase (status == 'ready').
        user_id:   The owner's user ID (used in feed metadata).
        base_url:  Your backend's public base URL, e.g. https://api.listenify.app
                   Used to build the self-link for the feed.

    Returns:
        A pretty-printed RSS 2.0 XML string.
    """
    rss = Element("rss", version="2.0")
    rss.set("xmlns:itunes", "http://www.itunes.com/dtds/podcast-1.0.dtd")
    rss.set("xmlns:content", "http://purl.org/rss/1.0/modules/content/")
    rss.set("xmlns:atom", "http://www.w3.org/2005/Atom")

    channel = SubElement(rss, "channel")

    # ── Channel metadata ─────────────────────────────────────────────────────
    SubElement(channel, "title").text = "My Listenify Podcasts"
    SubElement(channel, "link").text = "https://listenify-frontend.vercel.app"
    SubElement(channel, "description").text = (
        "AI-generated podcast episodes from research papers, created with Listenify."
    )
    SubElement(channel, "language").text = "en"
    SubElement(channel, "lastBuildDate").text = _fmt_rfc2822(
        podcasts[0]["created_at"] if podcasts else datetime.now(timezone.utc).isoformat()
    )

    image = SubElement(channel, "itunes:image")
    image.set("href", f"{base_url}/cover.png")  # must be public URL

    # Atom self-link (some validators require this)
    atom_link = SubElement(channel, "atom:link")
    atom_link.set("href", f"{base_url}/rss/{token}")
    atom_link.set("rel", "self")
    atom_link.set("type", "application/rss+xml")

    SubElement(channel, "itunes:author").text = "Listenify"
    SubElement(channel, "itunes:explicit").text = "false"

    itunes_owner = SubElement(channel, "itunes:owner")
    SubElement(itunes_owner, "itunes:name").text = "Listenify User"

    itunes_cat = SubElement(channel, "itunes:category")
    itunes_cat.set("text", "Science")

    # ── Episodes ─────────────────────────────────────────────────────────────
    for pod in podcasts:
        audio_url = pod.get("audio_url", "")
        if not audio_url:
            continue  # skip episodes without audio

        item = SubElement(channel, "item")

        title = pod.get("title") or f"Episode — {pod.get('language', 'en').capitalize()}"
        SubElement(item, "title").text = title

        guid = SubElement(item, "guid")
        guid.set("isPermaLink", "false")
        guid.text = pod.get("job_id", pod.get("id", ""))

        SubElement(item, "pubDate").text = _fmt_rfc2822(pod.get("created_at", ""))

        # Build a readable description from show notes if available
        show_notes = pod.get("show_notes") or {}
        summary_parts = []
        if isinstance(show_notes, dict):
            if show_notes.get("summary"):
                summary_parts.append(show_notes["summary"])
            key_terms = show_notes.get("key_terms", [])
            if key_terms:
                terms_str = ", ".join(
                    t["term"] if isinstance(t, dict) else str(t)
                    for t in key_terms[:6]
                )
                summary_parts.append(f"Key terms: {terms_str}")
        description = " | ".join(summary_parts) if summary_parts else "Generated by Listenify."
        SubElement(item, "description").text = description
        SubElement(item, "itunes:summary").text = description

        # Metadata tags
        SubElement(item, "itunes:duration").text = ""  # fill if you store duration
        SubElement(item, "itunes:explicit").text = "false"

        lang = pod.get("language", "english")
        diff = pod.get("difficulty", "")
        length = pod.get("length", "")
        SubElement(item, "itunes:subtitle").text = (
            f"{lang.capitalize()} · {diff} · {length}"
        )

        # The enclosure is what makes it a real podcast episode
        enclosure = SubElement(item, "enclosure")
        enclosure.set("url", audio_url)
        enclosure.set("type", "audio/mpeg")
        enclosure.set("length", "0")  # 0 is valid; fill with file size bytes if stored

        if pod.get("source_url"):
            SubElement(item, "link").text = pod["source_url"]

    raw = tostring(rss, encoding="unicode", xml_declaration=False)
    pretty = parseString(f'<?xml version="1.0" encoding="UTF-8"?>{raw}').toprettyxml(
        indent="  ", encoding=None
    )
    # toprettyxml adds its own declaration — strip the duplicate
    lines = pretty.splitlines()
    return "\n".join(lines[1:] if lines[0].startswith("<?xml") else lines)